[[headers]]
  for = "https://myquickmemo.netlify.app"
  [headers.values]
    Access-Control-Allow-Origin= "https://myquickmemo.netlify.app"
    Access-Control-Allow-Credentials="true"

    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS,PATCH"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"


[[redirects]]
  from = "/*"
  to = "/"
  status = 200